% setup_project.m  One-time bootstrap that creates a real MATLAB Project
% (Bmsengineeringassistant.prj) wired to startup.m for path management.
%
% Run once after cloning. Subsequent sessions just open the .prj.

here = fileparts(mfilename('fullpath'));
prjFile = fullfile(here, 'Bmsengineeringassistant.prj');

if isfile(prjFile)
    error('setup_project:exists', ...
        'Project already exists at %s. Delete it first to recreate.', prjFile);
end

prj = matlab.project.createProject( ...
    'Folder', here, ...
    'Name',   'BmsEngineeringAssistant');

folders = { ...
    'model/plant/models', 'model/plant/params', ...
    'model/bms/master', 'model/bms/slave', 'model/bms/common', ...
    'model/fault_predictor/inference', 'model/fault_predictor/models', ...
    'model/system/models', 'model/system/params', ...
    'validator', ...
    'validator/mil', 'validator/mil/tests/plant', 'validator/mil/tests/bms', 'validator/mil/tests/predictor', ...
    'validator/sil', 'validator/sil/tests', ...
    'validator/pil', 'validator/pil/tests', ...
    'validator/compare', ...
    'ai/fault_prediction/scripts/matlab' ...
};
w = warning('off', 'MATLAB:addpath:nameNonexistentOrNotADirectory');
cleanup = onCleanup(@() warning(w));
for i = 1:numel(folders)
    f = fullfile(here, folders{i});
    if isfolder(f), addPath(prj, f); end
end

prj.addFile(fullfile(here, 'startup.m'));
prj.addStartupFile(fullfile(here, 'startup.m'));
close(prj);

fprintf('Project created at %s\n', prjFile);
