% startup.m  Path setup invoked when MATLAB is launched in this folder
% (or when the project file Bmsengineeringassistant.prj is opened, via
% its Startup file hook).
%
% Adds every source folder needed by the model, validator and AI helpers
% to the MATLAB path, then runs init_system to populate the base
% workspace with parameters from model/system/params/init_system.m.

here = fileparts(mfilename('fullpath'));

paths = { ...
    fullfile(here, 'model', 'plant',           'models'), ...
    fullfile(here, 'model', 'plant',           'params'), ...
    fullfile(here, 'model', 'bms',             'master'), ...
    fullfile(here, 'model', 'bms',             'slave'), ...
    fullfile(here, 'model', 'bms',             'common'), ...
    fullfile(here, 'model', 'fault_predictor', 'inference'), ...
    fullfile(here, 'model', 'fault_predictor', 'models'), ...
    fullfile(here, 'model', 'system',          'models'), ...
    fullfile(here, 'model', 'system',          'params'), ...
    fullfile(here, 'validator'), ...
    fullfile(here, 'validator', 'plant'), ...
    fullfile(here, 'validator', 'plant', 'tests'), ...
    fullfile(here, 'validator', 'mil'), ...
    fullfile(here, 'validator', 'mil', 'tests', 'bms'), ...
    fullfile(here, 'validator', 'mil', 'tests', 'predictor'), ...
    fullfile(here, 'validator', 'sil'), ...
    fullfile(here, 'validator', 'sil', 'tests'), ...
    fullfile(here, 'validator', 'pil'), ...
    fullfile(here, 'validator', 'pil', 'tests'), ...
    fullfile(here, 'validator', 'cov'), ...
    fullfile(here, 'validator', 'compare'), ...
    fullfile(here, 'analyzer'), ...
    fullfile(here, 'orch'), ...
    fullfile(here, 'app'), ...
    fullfile(here, 'app', 'figures'), ...
    fullfile(here, 'ai', 'fault_prediction', 'scripts', 'matlab') ...
};
for i = 1:numel(paths)
    if isfolder(paths{i}), addpath(paths{i}); end
end

initFile = fullfile(here, 'model', 'system', 'params', 'init_system.m');
if isfile(initFile)
    evalin('base', sprintf('run(''%s'')', initFile));
end

clear here paths i initFile
