function trip = make_trip(trips_meas, id)
% Build a trip struct from a measured trip in trips_meas.
    if ~isfield(trips_meas, id)
        error('fp:missingTrip', 'Trip %s not found.', id);
    end
    tr = trips_meas.(id);
    t  = double(tr.time_s) - double(tr.time_s(1));
    trip = struct( ...
        'trip_id',      id, ...
        'duration_s',   t(end), ...
        'time_s',       t, ...
        'I_A',          double(tr.I_A), ...
        'T_amb_C',      double(tr.T_amb_C), ...
        'SoC_init_pct', double(tr.SoC_pct(1)), ...
        'T_init_C',     double(tr.T_cell_C(1)));
end
