function m = editable_models()
% orch.editable_models -- registry of user-editable Simulink models.
repo = orch.repo_root();
m = struct( ...
    'name',  {'bms_master', 'bms_slave', 'fault_predictor'}, ...
    'label', {'BMS Master', 'BMS Slave', 'Fault Predictor (LSTM)'}, ...
    'src',   {fullfile(repo,'model','bms','master','bms_master.slx'), ...
              fullfile(repo,'model','bms','slave','bms_slave.slx'), ...
              fullfile(repo,'model','fault_predictor','models','fault_predictor.slx')} );
end
