function s = scenarios()
% orch.scenarios -- catalog of selectable test scenarios per validation path.
%
% Returns a struct array with fields:
%   key   -- short identifier used by the UI dropdown
%   label -- human-readable label
%   path  -- 'mil' | 'sil' | 'pil'
%   filter-- glob filter forwarded to mil.run / sil.run / pil.run
%
% MIL is grouped by BMS subsystem (VMON, TMON, IMON, FSM, SOC, SOH, BAL,
% THM, PWR, WDG, HWP, AGG) plus the predictor suite. SIL and PIL are
% small (1 / 2 tests) and stay flat ('All').
%
% A 'cov' pseudo-path runs Simulink dead-code coverage on top of MIL.

mil_groups = { ...
    'all',  'All BMS + predictor',          ''                    ; ...
    'vmon', 'Voltage monitoring (VMON)',    'REQ_LL_BMS_VMON_*'   ; ...
    'tmon', 'Temperature monitoring (TMON)','REQ_LL_BMS_TMON_*'   ; ...
    'imon', 'Current monitoring (IMON)',    'REQ_LL_BMS_IMON_*'   ; ...
    'fsm',  'Severity FSM',                 'REQ_LL_BMS_FSM_*'    ; ...
    'soc',  'SoC estimator',                'REQ_LL_BMS_SOC_*'    ; ...
    'soh',  'SoH estimator',                'REQ_LL_BMS_SOH_*'    ; ...
    'bal',  'Balancing',                    'REQ_LL_BMS_BAL_*'    ; ...
    'thm',  'Thermal control',              'REQ_LL_BMS_THM_*'    ; ...
    'pwr',  'Power limits',                 'REQ_LL_BMS_PWR_*'    ; ...
    'wdg',  'Watchdog',                     'REQ_LL_BMS_WDG_*'    ; ...
    'hwp',  'Hardware protection',          'REQ_LL_BMS_HWP_*'    ; ...
    'agg',  'Signal aggregator',            'REQ_LL_BMS_AGG_*'    ; ...
    'prd',  'Predictor suite',              'REQ_LL_PRD_*'        };

s = struct('key',{},'label',{},'path',{},'filter',{});
for i = 1:size(mil_groups,1)
    s(end+1) = struct('key',mil_groups{i,1},'label',mil_groups{i,2}, ...
                      'path','mil','filter',mil_groups{i,3}); %#ok<AGROW>
end
s(end+1) = struct('key','all','label','SIL equivalence (bms_master)', ...
                  'path','sil','filter','');
s(end+1) = struct('key','all','label','PIL all (LSTM match + WCET)', ...
                  'path','pil','filter','');
s(end+1) = struct('key','prd','label','PIL predictor only',          ...
                  'path','pil','filter','REQ_LL_PIL_PRD_*');
s(end+1) = struct('key','wcet','label','PIL WCET only',              ...
                  'path','pil','filter','REQ_LL_RT_WCET_*');
end
